workspace:
  base: /go
  path: src/github.com/kevin7674/DNN-TEST

pipeline:
  backend:
    image: golang
    commands:
      - go get -v #github.com/kevin7674/DNN-TEST/test  
      #- go run -v test/main.go
      - go build -v 
      - go test -v test/main_test.go test/main.go 
 
  publish:
    image: plugins/docker
    repo: 100.86.2.10:32190/bar
    tags: [ 1.0.0, 1.0, latest ]

 

+branches: master

