workspace:
  base: /go
  path: src/github.com/kevin7674/DNN-TEST

pipeline:
  backend:
    image: golang
    commands:
      - go get -v #github.com/kevin7674/DNN-TEST/test
      - go test -v test/main_test.go test/main.go   
      #- go run -v test/main.go
      - go build -v 
  repo: eisenxu/realtopper-app
 

+branches: master

