workspace:
  base: /go
  path: src/github.com/kevin7674/DNN-TEST

pipeline:
  backend:
    image: golang
    commands:
      - go get -v #github.com/kevin7674/DNN-TEST/test
      #- go build -v main.go
      - go test -v test/main_test.go ./main.go   
      #- go run -v main.go

+branches: master

