#workspace:
  #base: /go
  #path: src/github.com/kevin7674/DNN-TEST/hello.go
  
pipeline:
  build:
    image: golang:latest
    commands:
      - go get 
      - go test
      - go build



