workspace:
  base: /go
  path: src/github.com/kevin7674/DNN-TEST

pipeline:
  backend:
    image: golang
    commands:
      - go get -v
      - go build -v main.go
      - go test -v test  
      - go run -v main.go

+branches: master

