workspace:
  base: /go
  path: src/github.com/kevin7674/DNN-TEST

pipeline:
  backend:
    image: golang
    commands:
      - go get -v github.com/kevin7674/DNN-TEST/test
      - go build -v test/main.go
      - go test -v . test  
      - go run -v test/main.go

+branches: master

