workspace:
  base: /go
  path: src/github.com/kevin7674/DNN-TEST

pipeline:
  backend:
    image: golang
    commands:
      - go get
      - go build main.go
      - go test      
      
  #deps:
    #image: golang:latest
    #commands:
      #- go get
      #- go test
  #build:
    #image: node:latest
    #commands:
      #- go build      

+branches: master

